const styles = {
  page: {
    minHeight: "100vh",
    background: "#f5f7fb",
    padding: "24px",
    fontFamily:
      "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    color: "#1f2933",
  },
  container: {
    maxWidth: "1100px",
    margin: "0 auto",
  },
  header: {
    marginBottom: "24px",
  },
  title: {
    margin: 0,
    fontSize: "26px",
    fontWeight: 700,
    color: "#111827",
  },
  subtitle: {
    marginTop: "8px",
    color: "#4b5563",
    fontSize: "14px",
  },
  card: {
    background: "#ffffff",
    borderRadius: "12px",
    padding: "18px 20px",
    marginBottom: "18px",
    boxShadow: "0 8px 18px rgba(15, 23, 42, 0.06)",
    border: "1px solid #e5e7eb",
  },
  sectionTitle: {
    margin: 0,
    marginBottom: "12px",
    fontSize: "18px",
    fontWeight: 600,
    color: "#111827",
  },
  row: {
    display: "flex",
    gap: "16px",
    alignItems: "center",
  },
  label: {
    display: "block",
    fontSize: "13px",
    fontWeight: 500,
    color: "#374151",
    marginBottom: "4px",
  },
  select: {
    width: "100%",
    padding: "8px 10px",
    borderRadius: "8px",
    border: "1px solid #d1d5db",
    fontSize: "14px",
    outline: "none",
  },
  helperText: {
    marginTop: "6px",
    fontSize: "12px",
    color: "#6b7280",
  },
  graphPreview: {
    marginTop: "16px",
  },
  graphTitle: {
    margin: 0,
    marginBottom: "6px",
    fontSize: "15px",
    fontWeight: 600,
  },
  graphImageWrapper: {
    marginTop: "8px",
    borderRadius: "10px",
    border: "1px dashed #d1d5db",
    padding: "10px",
    textAlign: "center",
    background: "#f9fafb",
  },
  graphImage: {
    maxWidth: "100%",
    maxHeight: "280px",
    borderRadius: "8px",
    display: "block",
    margin: "0 auto",
  },
  graphFallback: {
    fontSize: "12px",
    color: "#9ca3af",
  },
  code: {
    fontFamily: "monospace",
    background: "#f3f4f6",
    padding: "2px 5px",
    borderRadius: "4px",
    fontSize: "12px",
  },
  schemaRow: {
    display: "flex",
    gap: "24px",
    flexWrap: "wrap",
  },
  schemaCol: {
    flex: 1,
    minWidth: "220px",
  },
  schemaTitle: {
    margin: 0,
    marginBottom: "8px",
    fontSize: "15px",
    fontWeight: 600,
  },
  tagList: {
    listStyle: "none",
    padding: 0,
    margin: 0,
    display: "flex",
    flexWrap: "wrap",
    gap: "6px",
  },
  tag: {
    padding: "4px 8px",
    borderRadius: "999px",
    background: "#eef2ff",
    color: "#3730a3",
    fontSize: "12px",
  },
  tagListInline: {
    marginTop: "6px",
    display: "flex",
    flexWrap: "wrap",
    gap: "6px",
  },
  tagWarning: {
    padding: "3px 7px",
    borderRadius: "999px",
    background: "#fef3c7",
    color: "#92400e",
    fontSize: "12px",
  },
  textarea: {
    width: "100%",
    marginTop: "8px",
    padding: "8px 10px",
    borderRadius: "8px",
    border: "1px solid #d1d5db",
    fontSize: "13px",
    resize: "vertical",
  },
  warningBox: {
    marginTop: "10px",
    padding: "8px 10px",
    borderRadius: "8px",
    background: "#fffbeb",
    border: "1px solid #fcd34d",
    fontSize: "12px",
    color: "#78350f",
  },
  buttonRow: {
    marginTop: "14px",
    display: "flex",
    flexWrap: "wrap",
    gap: "10px",
    alignItems: "center",
    justifyContent: "space-between",
  },
  primaryButton: {
    padding: "8px 16px",
    borderRadius: "999px",
    border: "none",
    background: "#2563eb",
    color: "#ffffff",
    fontSize: "14px",
    fontWeight: 500,
    cursor: "pointer",
  },
  secondaryButton: {
    padding: "7px 14px",
    borderRadius: "999px",
    border: "1px solid #d1d5db",
    background: "#ffffff",
    color: "#111827",
    fontSize: "13px",
    cursor: "pointer",
  },
  fileControls: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  fileLabel: {
    padding: "7px 14px",
    borderRadius: "999px",
    border: "1px dashed #d1d5db",
    background: "#ffffff",
    color: "#111827",
    fontSize: "13px",
    cursor: "pointer",
  },
  errorBox: {
    padding: "10px 12px",
    borderRadius: "8px",
    background: "#fef2f2",
    border: "1px solid #fecaca",
    color: "#b91c1c",
    fontSize: "13px",
    marginBottom: "10px",
  },
  measuresGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))",
    gap: "12px",
    marginTop: "10px",
  },
  measureCard: {
    borderRadius: "10px",
    border: "1px solid #e5e7eb",
    padding: "10px 12px",
    background: "#f9fafb",
  },
  measureLabel: {
    fontSize: "13px",
    fontWeight: 600,
    color: "#111827",
  },
  measureValue: {
    marginTop: "4px",
    fontSize: "18px",
    fontWeight: 700,
    color: "#2563eb",
  },
  measureDesc: {
    marginTop: "4px",
    fontSize: "11px",
    color: "#6b7280",
  },
};

export default styles;
